### ISSUE TITLE
Remove etd_ms support

### ISSUE THREAD

**Issue by ldko** [unt-libraries/pyuntl#29]
At some point support for [etd-ms](http://www.ndltd.org/standards/metadata/etd-ms-v1.1.html) was added to pyuntl but not finished/perfected and never put into use in our system. Rather than fix it, since we aren't using it, we are going to cut it out of pyuntl.

**Comment by ldko** [comment]
After the Python2to3 PR gets merged into py3 branch, this can also be something for merging into py3 branch.

**Comment by madhulika95b** [comment]
To remove etd_ms support from pyuntl, I think, We can get rid of `etd_ms_structure.py`, `etd_test.py` totally, and in `untldoc.py` - `untlpy2etd_ms`, `generate_etd_ms_xml`, `etd_ms_dict2xmlfile`, `add_empty_etd_ms_fields`  and in `metadata_generator.py` - `etd_ms_py2dict` and elif part for ordering for degree children on etd_ms in `create_dict_subelement` and their corresponding tests.
