### ISSUE TITLE
Add hidden/unhidden helpers to pyuntl

### ISSUE THREAD

**Issue by vphill** [unt-libraries/pyuntl#37]
I was thinking that it might be useful to add a few common methods and properties to the python version of a UNTL record. 

I was thinking we could add two properties. 
`record.is_hidden` and `record.is_unhidden` that would return a `True` or `False` depending on the record. 

We could also add two methods, `record.make_hidden()` and `record.make_unhidden()` that could be used to adjust these values. 

I'm open to different language, formatting, and whatnot on the methods or property names.

**Comment by somexpert** [comment]
@vphill, how do you feel about changing `is_unhidden` and `make_unhidden` to `is_visible` and `make_visible`?

**Comment by ldko** [comment]
"hidden" is how it is referred to in the digi lingo, so it makes sense to me to use "hidden" over "visible".  I do wonder why we should need an `is_hidden` and `is_unhidden` though. It seems to me like `is_hidden` is enough if `is_unhidden` is always the opposite.

**Comment by ldko** [comment]
I guess it would not be opposite if the meta tag with hidden qualifier is missing (which in practice _shouldn't_ happen), but in that case, do we default to hidden? or should we say it is both not hidden and not unhidden as I believe is what happens in merge request now @vphill ?

**Comment by ldko** [comment]
@vphill said in #43 discussion that if no hidden qualifier is there, we should default to visible (unhidden).

**Comment by vphill** [comment]
I'm not deeply committed to having both `is_hidden` and `is_unhidden` I think it makes sense that we could just have `is_hidden` and then test against that for either case. 

I'm wondering if it would be useful to do some sort of warning (Stderr) for when a record has these methods called and doesn't have the meta.hidden value set.
