### ISSUE TITLE
Add coverage.eDate and coverage.sDate to the list of “can’t be used or edited”

### ISSUE THREAD

**Issue by ldko** [unt-libraries/pyuntl#53]
Mark wants to try the following on the test instance of the Edit system:

> Basically, we keep one qualifier for date (digitized) from being editable in the edit interface here - https://github.com/unt-libraries/pyuntl/blob/master/pyuntl/form_logic.py#L523
> I want to try to add coverage.eDate and coverage.sDate to the list of “can’t be used or edited”
> Because we are trying to remove those values from records with a preference for coverage.date and an EDTF range instead

**Comment by vphill** [comment]
Here is what records with a date.digitized value look like in the system - https://edit.digital.library.unt.edu/?fq=dc_date.digitized_count%3A1
 
If this works correctly, a similar thing will happen for the coverage.eDate and coverage.sDate records. 

* Here are some records with an eDate - https://edit.digital.library.unt.edu/?fq=dc_coverage.eDate_count%3A1
* Here are some records with a sDate - https://edit.digital.library.unt.edu/?fq=dc_coverage.sDate_count%3A1
